### ISSUE TITLE
Seems like NULL dates are getting assigned as Jan 01, 2001

### ISSUE THREAD

**Issue by jessebacon** [AndyButland/UmbracoMapper#1]
I have a null date coming in from a member property, but when it gets mapped to my view model with a nullable DateTime property the value is coming through as an actual datetime of Jan 01, 2001 (with ticks = 631139040000000000 instead of ticks = 0)

**Comment by AndyButland** [comment]
In my tests looks like you get Jan 01, 0001 - i.e. DateTime.MinValue.  Not sure why you are seeing 2001.

Still not ideal though - stems from a call to Umbraco's GetPropertyValue returning DateTime.MinValue when none is returned.  That said seems to me we should return null if mapping to a nullable DateTime.

I've set this up - https://github.com/AndyButland/UmbracoMapper/commit/7bdbe0b5d30193a79304a3159342355e7264e7d3 -  (just in source code for now, not yet updated NuGet or our).  If you can build the latest master branch and copy over the UmbracoMapper.dll, appreciate hearing if that solves the issue for you.

**Comment by AndyButland** [comment]
I've released this update on NuGet and our, version 1.4.18.

**Comment by jessebacon** [comment]
Sorry I wasn't able to test this initially. Thanks so much for a quick response on this! All the best!
