### ISSUE TITLE
A stored 'false' value for a boolean mapping is overridden by a default value set to 'true'

### ISSUE THREAD

**Issue by Ziiiiiiiiit** [AndyButland/UmbracoMapper#10]
Steps to reproduce:
Mark a bool property with a PropertyMappingAttribute with DefaultValue = true.
Store a false value for the property on the content that should be mapped.
Map property with UmbracoMapper.

Result:
During mapping the property will be set to true.

Expected result:
The default value should not be applied when there is a stored false value for the property. The property should be set to false.

Reason:
Mapping code applies default values after the content mapping, at which point the check to see if a mapping previously occured fails to differentiate a false that is actually set from a stored value from the false that is the default value of the bool type. I assume that the problem would be the same if I tried to set an integer value to 0 with a default value if 1. The 0 would then always be overridden as well.

Suggested solution:
First apply default values, then apply content mapping. Not the other way around.

**Comment by AndyButland** [comment]
Thanks for the report (and diagnosis!).  I'm away at the moment but should be able to get to fixing this at the weekend.

**Comment by AndyButland** [comment]
This should be resolved now - see v2.0.5 on our.umbraco.org or NuGet.

**Comment by Ziiiiiiiiit** [comment]
I have tested this with v2.0.5, and it works like a charm! Thank you very much for the extremely rapid response and solution!
