### ISSUE TITLE
Overriding a default mapping

### ISSUE THREAD

**Issue by Myster** [AndyButland/UmbracoMapper#12]
Hi Andy,
Thanks for the awesome project!
I have a question... 
Say I have a viewModel with a property of type Link ... most of the time I want one kind of mapping for properties of type Link. Which would be to get the picked content and get it's url. However sometimes I want something else, like 'find a page of a certain doctype' 

Here's what I tried:

For my default case I am doing this:
```c#
var mapper = new UmbracoMapper();
mapper.AddCustomMapping(typeof(Link).FullName, PropertyTypeMappings.SingleLink);
```

For my special case I am doing this:
```c#
[PropertyMapping(PropertyValueGetter = typeof(SearchPageGetter))]
public Link SearchPage { get; set; }
```

However the AddCustomMapper takes precedence.
Is there a way to override mappings made by calling AddCustomMapping to the UmbracoMapper?
Or is there a way to set a default mapping for a given type that is override-able?

Cheers.
Murray.

**Comment by AndyButland** [comment]
Hi Murray

I think this can work if you use the override to `AddCustomMapping` that allows you to pass the property name, and thus restrict the custom mapping to being used only on view model properties of a specific type _and_ a specific name.

So:

```
var mapper = new UmbracoMapper();
mapper.AddCustomMapping(typeof(Link).FullName, PropertyTypeMappings.SingleLink);
mapper.AddCustomMapping(typeof(Link).FullName, PropertyTypeMappings.SingleLink, "SearchPage");
```

Not tried it (in a while!) but believe that should work.

**Comment by Myster** [comment]
Hi Andy,
The suggested solution would require me to list all the property aliases in that mapper.
What I was looking for is a 'default' that would always take place, but could be over-ridden.

Currently I simply add attributes to everything that could be mapped two ways. which isn't a bad solution, but I was looking for some convention based solution for the really common cases.

Perhaps it would be a new feature, to have custom mappings only run if there is no PropertyMapping set. (there could be an option flag when defining CustomMappings to make it override-able)

**Comment by AndyButland** [comment]
I see.  Yes, sounds feasible to do, so take a look at the latest version (2.0.8) that I've pushed up to NuGet.

You can see how it works from the ["custom mappings" section of the documentation](https://github.com/AndyButland/UmbracoMapper#custom-mappings), starting from _"For the finest control, it's also possible to..."_

**Comment by Myster** [comment]
Hi Andy, 
Thanks for working on that so quickly... We aren't using the dictionary method, we're using the attributes to add custom mappings, is it possible to extend this to include attribute mappings?

We use both `IPropertyValueGetter` style:
`[PropertyMapping(PropertyValueGetter = typeof(PodLinkPropertyValueGetter))]`
and the `IMapFromAttribute `style:
`[MapFromAnythingToLink]`

**Comment by AndyButland** [comment]
Going to close this off as has been a while and discussed functionality has been implemented and released.
