### ISSUE TITLE
Multiple Attributes

### ISSUE THREAD

**Issue by Myster** [AndyButland/UmbracoMapper#13]
Hi,
I have this model:
```c#
[PropertyMapping(SourcePropertiesForCoalescing = new[] {"metaTitle", "title", "Name"})]
[MapFromStarMarkdownToPlainText]
public string Title { get; set; }
```
here's the attribute:
```c#
[AttributeUsage(AttributeTargets.Property)]
public class MapFromStarMarkdownToPlainTextAttribute : Attribute, IMapFromAttribute
{
	public void SetPropertyValue<T>(object fromObject, PropertyInfo property, T model, IUmbracoMapper mapper)
	{
		var rawValue = fromObject as string;
		property.SetValue(model, rawValue?.FromStarMarkdownToPlainText());
	}
}
```

But the attribute over-rides the sourcePropertiesForCoalescing and always uses the 'title'

(using version 2.0.8)

**Comment by AndyButland** [comment]
Think I've got this working.  Would you mind testing it with your solution using [this dll](https://www.dropbox.com/s/97atzp0bpvo98rg/Zone.UmbracoMapper.zip?dl=0) please?  If all OK, I'll push another release.

**Comment by Myster** [comment]
Hi Andy, It does not seem to do what I expect, my results are the same as before.
Asside: In what order would the operations be performed? In my case it's obvious to do the coalesce first, but I guess other cases aren't obvious, do they work in order they are in the source code?

**Comment by AndyButland** [comment]
I'm afraid I'm seeing it working OK.  Maybe you could have a look at the last couple of commits I've done on master branch, particularly the unit and web based test, and see if you can see if I'm missing something.  

The order though is that the `IMapFromAttribute` is used, but then when it returns it's results, they are coalesced.  So you should get the first non-null value mapped.

**Comment by AndyButland** [comment]
Going to close this off.  Have pushed up version 2.0.9 which (I think) includes this amend.
