### ISSUE TITLE
Incompatible with Umbraco 8

### ISSUE THREAD

**Issue by paulnewzealand** [AndyButland/UmbracoMapper#14]
Hi, 

I've just tried using the excellent UmbracoMapper package in Umbraco 8 and I get the following error when I try to map a model to the mapper variable:

`var mapper = new Zone.UmbracoMapper.UmbracoMapper()`

_"Reference to type 'IPublishedContent' claims it is defined in 'Umbraco.Core', but it could not be found"_

Seems like Umbraco 8 doesn't play nice with UmbracoMapper.

Do you have any any plans to create a version that does?

Many Thanks, Paul

**Comment by AndyButland** [comment]
Hi Paul - as you've found, Umbraco 8 isn't supported with the package no.  I'll need to look at creating a new version as the APIs have changed, so it won't be compatible with this package.

I do plan to take a look at creating a version that does shortly though yes.  Hopefully it won't be too difficult but we'll see when I get into it!

**Comment by paulnewzealand** [comment]
Thanks Andy, really appreciate the swift response, I know you're a busy man.

It seems there is going to be a lot of this kind of thing with Umbraco 8, might be a bumpy start to the Umbraco 8 era :)

Thanks again, Paul

**Comment by AndyButland** [comment]
I've just released a new version of the package that supports V8.  If you fancied giving it a try I'd appreciate any feedback.  As well as in the updated [read me,](https://github.com/AndyButland/UmbracoMapper/) details are in this [blog post](https://web-matters.blogspot.com/2019/03/umbraco-mapper-new-releases-supporting-v8.html).

**Comment by paulnewzealand** [comment]
Hi,

I'll do that, thanks Andy.

I'll let you know how I get on.

Cheers, Paul


Blue Sun Digital

Paul Bowen - Director / Web Developer

Mobile: +64 (0)21 167 1477

Web: www.bluesundigital.com

Email: paul@bluesundigital.com


Blue Sun Digital is the new name for Select UX - Please update your contact
details for me.

**Comment by paulnewzealand** [comment]
Hi Andy,

I put a comment on your blog but some initial work on my Umbraco 8 project
is looking good, I have content mapping :)

Thanks for your effort on this and the quick release.

Cheers, Paul


Blue Sun Digital

Paul Bowen - Director / Web Developer

Mobile: +64 (0)21 167 1477

Web: www.bluesundigital.com

Email: paul@bluesundigital.com


Blue Sun Digital is the new name for Select UX - Please update your contact
details for me.
