### ISSUE TITLE
Upgrade to 8.1.0 Breaks Page Types Using Umbraco Mapper

### ISSUE THREAD

**Issue by john-mckillip** [AndyButland/UmbracoMapper#16]
I upgraded this morning and am getting this error now when calling UmbracoMapper.Map():
Method not found: 'Umbraco.Core.Models.PublishedContent.PublishedContentType Umbraco.Core.Models.PublishedContent.IPublishedElement.get_ContentType()'. Looks like some things changed with IPublishedContent in the latest minor release.

**Comment by AndyButland** [comment]
I had on my list for the weekend to see what the breaking changes in 8.1 might mean for my packages!  Obviously not good.  Will take a look to see what needs updating.

**Comment by john-mckillip** [comment]
Sounds good. Thanks Andy!

**Comment by rasolo** [comment]
Same here problem here. They mention changes in PublishedContentType here:
https://our.umbraco.com/documentation/getting-started/setup/upgrading/version-specific

> If you've got your generated models in your solution you will need to update them after upgrade: PublishedContentType will need to be replaced with IPublishedContentType. If you have a implementintation of the PropertyValueConverter class, you need to replaced all references to PublishedPropertyType with IPublishedPropertyType within that class. Only after you do that will your solution build again.

**Comment by rasolo** [comment]
I pulled this repo and searched for PublishedContentType and PropertyValueConverter, I could not find any references to these so the problem does not lie here.

**Comment by john-mckillip** [comment]
It may just be that the versions of UmbracoCms.Core and UmbracoCms.Web need to be updated in the package. I just forked the repo and updated the packages in the V8 and V8.Tests projects. It builds and all the unit tests pass. I am going to drop the dll generated into my project and see if it runs.

**Comment by john-mckillip** [comment]
That worked. Looks like it's just the version conflict with the Umbraco packages.

**Comment by john-mckillip** [comment]
@AndyButland I can do a PR but it's probably just easier for you to just upgrade the packages since you have to create a nuget package. Let me know.

**Comment by AndyButland** [comment]
Thanks for checking this @john-mckillip - good to hear that's all that's needed.  Agree I can just as easily do this, so will hopefully do so at the weekend and get a new release out.

**Comment by rasolo** [comment]
Really smart @john-mckillip! I just tried it and it works. 
@AndyButland Curious how you will solve this. Will you have to create a new project Zone.UmbracoMapper.V8.1 for this fix? Because simply upgrading the V8 project will make breaking changes for those still on 8.0.*, right?

Otherwise I will just have to wait and see how you solve it. Thanks for this great repo.

**Comment by AndyButland** [comment]
Planning to just upgrade the existing V8 project.  So anyone who wants the newer versions of the package, would also have to upgrade Umbraco to 8.1.  I think that's reasonable.  I've created separate V7 and V8 projects conscious that not everyone will want to/be able to justify upgrading to Umbraco 8, and might still benefit from updates to the package.  But not intending to do that for each minor Umbraco release.  Moving forward, they _should_ be non-breaking, and in this case it's not a big ask for someone already on Umbraco 8.0 to update to 8.1.

**Comment by rasolo** [comment]
Thanks for the explanation. Sounds reasonable indeed!

**Comment by AndyButland** [comment]
I've applied the same as @john-mckillip and can confirm looks to resolve the issue.  Have created a new release - [4.1.0 on NuGet](https://www.nuget.org/packages/UmbracoMapper/4.1.0) and on [our](https://our.umbraco.com/packages/developer-tools/umbraco-mapper/).  Thanks for the reports and investigation on this @rasolo too.
