### ISSUE TITLE
unit Test Media file on view model documentation

### ISSUE THREAD

**Issue by rasolo** [AndyButland/UmbracoMapper#17]
Hi,
I can not find any documentation on how to unit test that a media file prop on the view model has been mapped in the controller for the page. 

I have tried to do this myself but was unsuccessful. I don't know how to do it since media file is not an official umbraco property.  Perhaps this is not possible? But if it is, please add documentation on how to do it.

**Comment by AndyButland** [comment]
Hi - think it should be possible.  Will take a look to add one to the tests in the source code (where really there should be one anyway of course!).

**Comment by AndyButland** [comment]
You can find one of these in source now - see [here](https://github.com/AndyButland/UmbracoMapper/blob/master/Zone.UmbracoMapper.V8.Tests/UmbracoMapperTests.cs#L1068).

**Comment by rasolo** [comment]
Thanks a lot!
