### ISSUE TITLE
[Umbraco 7] RadioButtonList mapping is broken

### ISSUE THREAD

**Issue by rasolo** [AndyButland/UmbracoMapper#19]
Radio button list property does not map correctly in version 7.13.2. It works perfect in 8.1.4.

Problem: The mapping creates a number for the property instead of the actual value chosen.

Reproduce: 

- Create a RadioButtonList property in Umbraco
-  Create a property for your document type in the code that maps to it. (type: string)
-  Add the property in your document type and chose one of the options, save page.
- Print the value of the property or debug and watch the value and it will be a number instead of the value.

![radiolist](https://user-images.githubusercontent.com/28714079/65067607-2d940b00-d987-11e9-8d63-327b2955989a.PNG)
The value here should be "External"

Is it possible to fix this? Or am I doing it wrong for version 7?

Kind regards,
Rasmus

**Comment by AndyButland** [comment]
This looks like a difference in Umbraco version behaviour.

If you compare the documentation pages for radio button list for [v8](https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/RadioButton-List/) and [v7](https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/RadioButton-List/index-v7) you can see that natively, only V8 returns the label, whearas V7 returns the value.

For V7 looks like you would have to wrap your reference in the view with have to call `Umbraco.GetPreValueAsString(Model.RadioList)`.

I'll have a look though whether it's feasible to get the mapper to do that - perhaps an attribute value indicating that this conversion from the prevvalue should happen for a given view model property.

**Comment by rasolo** [comment]
> This looks like a difference in Umbraco version behaviour.
> 
> If you compare the documentation pages for radio button list for [v8](https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/RadioButton-List/) and [v7](https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/RadioButton-List/index-v7) you can see that natively, only V8 returns the label, whearas V7 returns the value.
> 
> For V7 looks like you would have to wrap your reference in the view with have to call `Umbraco.GetPreValueAsString(Model.RadioList)`.
> 
> I'll have a look though whether it's feasible to get the mapper to do that - perhaps an attribute value indicating that this conversion from the prevvalue should happen for a given view model property.

Thank you for the quick reply. I will use the GetPreValueAsString method for now. Would be nice if automapper added the value itself but its okay

**Comment by AndyButland** [comment]
I've just released version 3.0.3 that supports this now, if you add a `[PropertyMapping(MapFromPreValue = true)]` to your view model property.

**Comment by rasolo** [comment]
Thanks a lot!
