### ISSUE TITLE
umbraco v8 context in IPropertyValueGetters

### ISSUE THREAD

**Issue by shearer3000** [AndyButland/UmbracoMapper#20]
Hi

In Umbraco 8, I have a view model property decorated with a IPropertyValueGetter class. What it needs to do is hydrate a complex model using some umbraco context such as UmbracoContext.Media.GetById and UmbracoContext.Content.GetById (the data type is a multi url picker, so it could be a list of both media and/or content)
My question is, what is the best way of getting umbraco context (IUmbracoContextFactory) within my PropertyValueGetter class?

The umb7 way seemed to be to “reach into” umbraco and grab what you wanted i.e. “var umbracoHelper = new UmbracoHelper(UmbracoContext.Current);”
But in umb8 it seems that we really need to inject the umbraco context (i.e. IUmbracoContextFactory) or at least pass it in somehow.

What are peoples thoughts here?

Thanks
Andrew

**Comment by AndyButland** [comment]
Not sure if this is something I can see how to support I'm afraid (though happy for any advice).  When an `IPropertyValueGetter` is attached to a single property, it's attached as a type, which then needs to be instantiated via reflection when used.  This is done on the assumption that the constructor doesn't have any parameters, but to use DI, of course you'd be introducing them.

As I understand the "reach out" method (service location) is still available in Umbraco 8, so you should still be able to use that without any real issues other than not adhering to what many people would consider the better practice of using dependency injection.

When I introduced `IPropertyValueGetter` it was originally to support Vorto - just to be able to replace the default `content.GetPropertyValue()` with a different call.  So not so much to be doing particularly complex logic within.  Can't see any reason why you shouldn't, but figured worth mentioning that's the only use case I've personally used it for.

**Comment by shearer3000** [comment]
Hi Andy 

Thanks for your reply and pointers.
Yes I suspected as much but thought I should ask anyway in case there was an approach I didn’t know of 😊

You are right, the instantiation via reflection means there would be no opportunity for me to register the PropertyValueGetter class with the Umbraco LightInject DI container as it’s not resolved from there anyway.

The “reach out” method in v7 was “var context = UmbracoContext.Current;”
And is still available in v8 as “var context = Umbraco.Web.Composing.Current.UmbracoHelper;”

It sounds like I should also double check my teams previous approach in using IPropertyValueGetters as it sounds like its not the primary way of using the mapper.

Thanks
Andrew
