### ISSUE TITLE
Mapping of GetCropUrl

### ISSUE THREAD

**Issue by rasolo** [AndyButland/UmbracoMapper#22]
Hi,

There is a method in Umbraco: GetCropUrl. You can use this method to retrieve the crop url(s) you have created for a page using the ImageCropper property editor. In this method you can pass (in my example) two parameters:

1. Document type alias
2. Media crop alias

This is an extension method on the IPublishedContent of the page.

Issue: I am unable to use UmbracoMapper method: MapCollection since I need to use the method .GetCropUrl on the IPublishedContent. So instead what I am doing is a foreach loop of every IPublishedContent page and using the UmbracoMapper Map method for every page in the loop, and calling .GetCropUrl there.

What I would like is automatic mapping of GetCropUrl as well. Is it possible for this to be added or does it already exist?

So instead of this code:

`

		public IEnumerable<BlogPostPage.BlogPostPage> GetMappedBlogPosts(IEnumerable<IPublishedContent> blogPostPagesAsPublishedContent)
		{
			var blogPostPages = new List<BlogPostPage.BlogPostPage>();

			foreach (var blogPostPagePublishedContent in blogPostPagesAsPublishedContent)
			{
				var blogPostPage = new BlogPostPage.BlogPostPage();
				this.UmbracoMapper.Map(blogPostPagePublishedContent, blogPostPage);

				blogPostPage.TeaserMediaUrl =
					blogPostPagePublishedContent.GetCropUrl(BlogPostPagePropertyAlias.TeaserMedia,
						BlogPostPageMediaCropAliases.StartPage);
				blogPostPages.Add(blogPostPage);
			}

			return blogPostPages;
		}

`

I would like to use this:

`

	public IEnumerable<BlogPostPage.BlogPostPage> GetMappedBlogPosts(IEnumerable<IPublishedContent> blogPostPagesAsPublishedContent)
		{
			var blogPostPages = new List<BlogPostPage.BlogPostPage>();

			this.UmbracoMapper.MapCollection(blogPostPagesAsPublishedContent, blogPostPages);

			return blogPostPages;
		}

`

Maybe this is impossible or would take too long?

Also, in the view model, is it possible for you to create an attribute you can put on a string property for the crop url you want, where you send in the document type alias and media crop alias to the attribute for automatic mapping?

Kind regards,
Rasmus

**Comment by AndyButland** [comment]
Think this should be possible by providing a custom attribute implementing `IMapFromAttribute`:

```
    using System;
    using System.Reflection;
    using Umbraco.Core.PropertyEditors.ValueConverters;
    using Zone.UmbracoMapper.V8;
    using Zone.UmbracoMapper.V8.Attributes;

    [AttributeUsage(AttributeTargets.Property)]
    public class MapFromImageCropperAttribute : Attribute, IMapFromAttribute
    {
        public string CropName { get; set; }

        public void SetPropertyValue<T>(object fromObject, PropertyInfo property, T model, IUmbracoMapper mapper)
        {
            var imageCropperValue = fromObject as ImageCropperValue;
            if (imageCropperValue == null)
            {
                return;
            }


            property.SetValue(model, imageCropperValue.Src + imageCropperValue.GetCropUrl(CropName));
        }
    }
```

Then using it on the view model like this (assuming an document type field with the alias `imageCrop`:

```
        [PropertyMapping(SourceProperty = "imageCrop")]
        [MapFromImageCropper(CropName = "square")]
        public string ImageCropUrl { get; set; }
```

**Comment by rasolo** [comment]
@AndyButland 

Man thanks Andy it works! You are a genius!

Have a great day

**Comment by AndyButland** [comment]
Great - credit to @21robin12 really (he came up with this `IMapFromAttribute` idea).  

_Hi Robin - been a long time, hope all good with you!_

**Comment by 21robin12** [comment]
@AndyButland blast from the past!
