### ISSUE TITLE
How can I mock the new .Url() extension from Umbraco.Web?

### ISSUE THREAD

**Issue by rasolo** [AndyButland/UmbracoMapper#26]
Hi,

Worth a shot asking for help here.

A new release from Umbraco has made the old .Url property on IPublishedContent obsolete and has been replaced with an extension method instead. Using extension methods is not allowed in Moq so it will complain about that. If I wrap the extension method in a class it will complain about IPublishedContent. If I do not Moq Url UmbracoMapper will throw an exception saying that the IPublishedContent is null because the Url property is not set.

Is it possible to fix this? I will link to an issue on Github where I mention this too.

https://github.com/umbraco/Umbraco-CMS/pull/7550#issuecomment-694016659

Thanks,
Rasmus

**Comment by rasolo** [comment]
I tried looking in this UmbracoMapper project to see if it was solved but could not find an example

**Comment by AndyButland** [comment]
I think you'll need to look to mock the dependencies that the `Url()` extension method calls.  Namely the `IPublishedUrlProvider`.  So in your unit test, you'll call `Url()` as normal, but it will then call your mocked dependency.  I haven't tried this but think that's the general approach to tackle testing with extension methods.

**Comment by rasolo** [comment]
Thanks for the advice but it is too difficult :( I have looked at Moles and Smock but can't get it to work. I also looked at the tests project in Umbraco itself but there arent any examples there for solving this. I will have to live with it lol.
